# Generated by Django 6.0.2 on 2026-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('ckd_arrival_iea', models.CharField(blank=True, max_length=100)),
                ('prd_customer', models.CharField(blank=True, max_length=100)),
                ('daily_target', models.IntegerField(default=0)),
                ('total_units', models.IntegerField(default=0)),
            ],
        ),
    ]
