# Generated by Django 6.0.1 on 2026-02-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='series',
            field=models.CharField(choices=[('N', 'N-Series (Light Duty)'), ('F', 'F-Series (Medium Duty)')], default='F', max_length=1),
        ),
    ]
