# Generated by Django 6.0.1 on 2026-02-22 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productiontask_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
